entities:
  seaf.ia.data_objects:
    title: Объекты данных
    schema:
      type: object
      patternProperties:
        "[a-zA-Z0-9_]*(\\.[a-zA-Z0-9_]*)*$":
          type: object
          properties:
            title:
              title: Наименование
              type: string
            business_object:
              title: Родительский бизнес-объект
              $ref: "#/$rels/seaf.ia.business_objects.business_objects"
            master_system:
              title: АС, являющаяся мастер системой для объекта данных
              $ref: "#/$rels/components.component"
          required:
            - title
            - business_object
            - master_system
    objects:
      data_object:
        route: "/"
        title: Объект данных
        symbol: "do"
