entities:
  seaf.ia.business_objects:
    title: Бизнес-объекты
    schema:
      type: object
      patternProperties:
        "[a-zA-Z0-9_]*(\\.[a-zA-Z0-9_]*)*$":
          type: object
          properties:
            title:
              title: Наименование
              type: string
            processes:
              title: Используется в бизнес-процессах
              type: array
              items:
                $ref: "#/$rels/seaf.ba.processes.process"
          required:
            - title
            - processes
    objects:
      business_objects:
        route: "/"
        title: Бизнес-объект
        symbol: "busobj"